esphome:
  name: "node_1"
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "GRPUG_Demo"
  password: "0xdeadbeef"

web_server:
  port: 80

api:

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
